local ADDON_NAME, ns = ...
local GCDM = LibStub("AceAddon-3.0"):GetAddon(ADDON_NAME)

GCDM.CONST = {
	FONT_PATH = "Fonts\\FRIZQT__.TTF",
	FONT_OUTLINE = "OUTLINE",
	TEX_WHITE8X8 = "Interface\\Buttons\\WHITE8X8",
	TEX_CDM_SWIPE = "Interface\\HUD\\UI-HUD-CoolDownManager-Icon-Swipe",
	SWIPE_COLOR = { r = 0, g = 0, b = 0, a = 0.6 },
	GCD_SPELL_ID = 61304,

	VIEWERS = {
		ESSENTIAL = "EssentialCooldownViewer",
		UTILITY = "UtilityCooldownViewer",
		BUFF = "BuffIconCooldownViewer",
		BUFF_BAR = "BuffBarCooldownViewer",
	},

	REFRESH = {
		ALL = "ALL",
		STYLE = "STYLE",
		LAYOUT = "LAYOUT",
		GLOW = "GLOW",
		GROUPS = "GROUPS",
	},

	MIN_BAR_WIDTH = 200,

	DEFAULT_ICON_ZOOM = 0.08,
	DEFAULT_BORDER_SIZE = 1,
	DEFAULT_POWER_BAR_HEIGHT = 10,
	DEFAULT_POWER_BAR_GAP = 2,
	DEFAULT_BUFF_BAR_HEIGHT = 16,
	MIN_BUFF_BAR_HEIGHT = 4,
	DEFAULT_POWER_BAR_FONT_SIZE = 12,
	DEFAULT_INDEPENDENT_BAR_Y = -100,
	DEFAULT_VIEWER_POS_Y = 80,
	HOST_FRAME_LEVEL = 100,
	SIZE_EPSILON = 0.5,
	MIN_LIVE_ESSENTIAL_WIDTH = 40,

	LAYOUT_REAPPLY_IMMEDIATE = 0,
	LAYOUT_REAPPLY_DELAY = 0.15,
	LAYOUT_RETRY_AFTER_LOADING = 0.25,

	POWER_BAR_BG_COLOR = { r = 0.1, g = 0.1, b = 0.1, a = 0.95 },
	POWER_BAR_TICK_DEFAULTS = "25,50,75,100",
}

local VIEWERS = GCDM.CONST.VIEWERS
GCDM.CONST.COOLDOWN_VIEWER_NAMES = { VIEWERS.ESSENTIAL, VIEWERS.UTILITY }
GCDM.CONST.MANAGED_VIEWER_NAMES = { VIEWERS.ESSENTIAL, VIEWERS.UTILITY, VIEWERS.BUFF }
GCDM.CONST.ALL_VIEWER_NAMES = { VIEWERS.ESSENTIAL, VIEWERS.UTILITY, VIEWERS.BUFF, VIEWERS.BUFF_BAR }
